# Generated by Django 4.1.4 on 2023-04-16 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('summary', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(20)])),
                ('issue', models.IntegerField(null=True)),
                ('created_at', models.DateField()),
                ('completed_at', models.DateField()),
                ('state', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed'), ('dropped', 'dropped')], default='pending', max_length=20)),
                ('assignee', models.CharField(max_length=50)),
            ],
        ),
    ]
